### ISSUE TITLE
Razor @: error still broken after v1.7

### ISSUE THREAD

**Issue by walterDurin** [deanhume/html-minifier#24] opened 2016-04-06 17:02 UTC
I hate to be a thorn in anyone's side but v1.7 did not fix this issue, razor "@:" need to be on its own line or it breaks, it is still broken in 1.7, I don't know why it was closed as fixed when it is not. 

test:

@if (true) {
@:<p></p>
}

**Comment by 0xApp** [comment] 2016-05-29 19:56
@walterDurin consider using
```
@if (true){
    <text> you content here,
         some more content here
    </text>
}
```

> The <text> tag is an element that is treated specially by Razor. It causes Razor to interpret the inner contents of the <text> block as content, and to not render the containing <text> tag element (meaning only the inner contents of the <text> element will be rendered – the tag itself will not).  This makes it convenient when you want to render multi-line content blocks that are not wrapped by an HTML element.

[Check this](http://weblogs.asp.net/scottgu/asp-net-mvc-3-razor-s-and-lt-text-gt-syntax)

**Comment by ConcatenatedNonsense** [comment] 2016-06-23 15:25
Just tried the Minifier on the release code version of an existing project and it errored outright.
It seems it failed at the first @if statement.

**Comment by heldersepu** [comment] 2017-04-16 17:18
Look here:
https://github.com/deanhume/html-minifier/blob/master/ViewMinifier/StreamReaderExtension.cs#L54
I believe all we need to do is add a line:
declarations.Add("@if ", false);

**Comment by heldersepu** [comment] 2017-04-16 17:21
Can anyone attach a sample file to reproduce the error? 
Then we can add that file to the UnitTests...

**Comment by Deutschi** [comment] 2017-06-16 14:54
**Example 1:**

Input:
```
<div>
    @if (true)
    {
        @: this is normal text without html tag
    }
</div>
```

Output:
```
<div> @if (true) { @: this is normal text without html tag } </div>
```
The closing "}" is no longer recognized as syntax, because it's on the same line as the "@:"


**Example 2:**

Input:
```
<div>
	@switch (foo)
	{
		default:
			@: @Model.Name
			break;
	}
</div>
```

Output:
```
<div> @switch (foo) { default: @: @Model.Name break; } </div>
```
The "break" is no longer recognized as syntax, same as example 1.

**Comment by heldersepu** [comment] 2017-06-16 15:04
Thanks @Deutschi 
what would be the correct output on those examples?

**Comment by Deutschi** [comment] 2017-06-16 15:07
Valid output:

```
<div> @if (true) { @: this is normal text without html tag
} </div>
```

```
<div> @switch (foo) { default: @: @Model.Name
break; } </div>
```

Suggestion: The next line break after an "@:" should not be replaced.

**Comment by deanhume** [comment] 2017-06-26 15:37
This issue should be fixed with the latest release!

**Closed by deanhume** 2017-06-26 15:37 UTC
Labels: bug

**Comment by heldersepu** [comment] 2017-06-26 17:01
@deanhume 
I don't think this has been fixed yet...
